content_safety:
  severity_threshold: 2
  safe_responce: "I cannot generate a response to this request."

system_instructions:
  max_tokens: 4000

intent_classifier:
  use_slm_classifier: True
  max_tokens: 2
  temperature: 0
  top_p: 0.0

llm:
  max_past_messages: 10
  max_tokens: 150
  temperature: 0.5
  top_p: 0.5

slm:
  max_past_messages: 5
  max_tokens: 100
  temperature: 0.25
  top_p: 0.25

tools:
  tool_call_timeout_seconds: 10
  max_retries: 3
  backoff_seconds: 2

mcp:
  max_tool_response_length: 1000
  tool_call_timeout_seconds: 10
  max_retries: 3
  backoff_seconds: 2
  