content_safety:
  severity_threshold: 2
  safe_responce: "I cannot generate a response to this request."

system_instructions:
  max_tokens: 4000

support_agent:
  name: "support_agent"

billing_agent:
  name: "billing_agent"

llm:
  max_past_messages: 10
  max_tokens: 150
  temperature: 0.5
  top_p: 0.5